packages/platform/LICENSE, packages/platform/package.json, pnpm-lock.yaml
- move to the BNF npm scoped package
- add npm description
- add license
- fix dependencies
=> platform package ready to publish

packages/platform/src/App.tsx, packages/platform/src/editor/Editor.tsx, packages/platform/src/editor/plugins/ScriptureReferencePlugin.tsx
- split combined state properties into their own separate properties.
=> decouple state properties

.github/workflows/test-publish.yml, README.md, packages/perf-react/package.json, packages/perf-vanilla/package.json, packages/platform/README.md, packages/platform/package.json
- allow GHA npm publishing
- update READMEs
- add install, usage, demo & WDE, license
- fix `yalc` instructions
- remove anchor links, clicks worked locally but not in GH
- add license to `package.json`
=> improve publishing

packages/platform/package.json
- attempt to fix missing `dist` folder in npm package
=> attempt to fix missing `dist` folder

.github/workflows/test-publish.yml, packages/platform/package.json
- fix missing `dist` folder in npm package
=> platform-editor v0.0.5

packages/platform/src/App.tsx, packages/platform/src/index.ts, packages/shared/converters/usj/converter-test.data.ts, packages/shared/converters/usj/usj-to-usx.test.ts, packages/shared/converters/usj/usj-to-usx.ts, packages/shared/converters/usj/usx-to-usj.test.ts, packages/shared/converters/usj/usx-to-usj.ts, packages/shared/converters/usj/usx.model.ts
=> Convert USJ to USX

packages/platform/README.md, packages/platform/src/App.tsx, packages/platform/src/editor/adaptors/editor-usj-adaptor.test.ts, packages/platform/src/editor/adaptors/editor-usj.adaptor.ts, packages/platform/src/editor/adaptors/usj-editor-adaptor.test.ts, packages/platform/src/editor/adaptors/usj-editor.adaptor.ts, packages/platform/src/index.ts, packages/shared/converters/usj/converter-test.data.ts, packages/shared/converters/usj/usj.model.ts, packages/shared/data/WEB-PSA.usx.ts, packages/shared/nodes/scripture/usj/BookNode.ts, packages/shared/nodes/scripture/usj/ChapterNode.ts, packages/shared/nodes/scripture/usj/CharNode.ts, packages/shared/nodes/scripture/usj/ImmutableChapterNode.ts, packages/shared/nodes/scripture/usj/ImmutableVerseNode.ts, packages/shared/nodes/scripture/usj/MilestoneNode.ts, packages/shared/nodes/scripture/usj/NoteNode.ts, packages/shared/nodes/scripture/usj/ParaNode.ts, packages/shared/nodes/scripture/usj/UnknownNode.ts, packages/shared/nodes/scripture/usj/VerseNode.ts, packages/shared/nodes/scripture/usj/index.ts, packages/shared/nodes/scripture/usj/node.utils.ts
- fixes #39
**Note:** all the USJ nodes have been updated in the same repeated way.
=> handle unknown nodes & attributes

packages/platform/package.json, packages/platform/src/App.css, pnpm-lock.yaml
- cleanup CSS
- remove unused dependencies
=> cleanup `platform`

packages/perf-react/package.json, packages/perf-vanilla/package.json, packages/platform/package.json, packages/shared-react/package.json, packages/shared/package.json, pnpm-lock.yaml
- also fix shared package dependency location
=> fix `volta` inheritance

.codesandbox/tasks.json
- update to pnpm v9
- broken by #69
=> fix Codesandbox not working

packages/platform/README.md, packages/platform/src/App.tsx
=> Fix editor reload

packages/shared/nodes/scripture/usj/ParaNode.ts
- retain the formatting of the current `ParaNode` when the enter key is pressed
- also remove `updateDOM` (same as superclass)
- also add `importDOM` (different from superclass)
=> retain format on enter key

packages/platform/src/editor/Editor.tsx
=> platform - no toolbar when readonly

packages/platform/src/App.tsx, packages/platform/src/editor/ScriptureReferencePlugin.tsx
- to comply with Lexical conventions
- also swap BC control props
=> platform - add `$` to relevant functions

package.json, packages/scribe/.eslintrc.cjs, pnpm-lock.yaml
This is not currently causing a problem but if other eslint plugins are added it is a problem waiting to happen.
=> Fix eslint with prettier

packages/platform/README.md, packages/platform/src/App.tsx, packages/platform/src/editor/Editor.tsx, packages/platform/src/marginal/Marginal.tsx, packages/platform/src/marginal/comments/CommentPlugin.tsx, packages/shared-react/annotation/AnnotationPlugin.tsx, packages/shared-react/annotation/annotation.model.ts, packages/shared-react/annotation/selection.model.ts, packages/shared/nodes/features/TypedMarkNode.ts
- only collapse the cursor at the end for comments.
=> Platform set selection

packages/scribe/package.json
A mini scribe release to get some vscode features tested.
=> scribe v0.0.2

packages/scribe/README.md
=> Added README.md to scribe package

packages/scribe/package.json, pnpm-lock.yaml
=> using @biblionexus-foundation/scripture-utilities from npm package.

packages/platform/src/marginal/comments/CommentPlugin.css
=> 124 improve comment sidebar styling

packages/platform/src/editor/editor.css, packages/shared-react/plugins/TextDirectionPlugin.tsx
- ensure placeholder position matches where the cursor is (when there is no Scripture data)
=> fix platform placeholder position

packages/platform/scripts/consolidate_files.py, packages/platform/scripts/project_files.md, packages/platform/src/editor/Editor.tsx
- also add PY script to create an MD file to pass to AI tools
=> fix default USJ loading

packages/platform/.gitignore, packages/platform/src/editor/editor.css, packages/platform/src/editor/toolbar/ToolbarPlugin.tsx
- fixes #126
- fixed width and ellipsis
- also fix block display for BookNode
- also add git ignore in preparation for collaboration
=> platform: improve toolbar block width

packages/shared/nodes/scripture/usj/CharNode.ts, packages/shared/nodes/scripture/usj/MilestoneNode.ts, packages/shared/nodes/scripture/usj/NoteNode.ts, packages/shared/nodes/scripture/usj/ParaNode.ts, packages/shared/nodes/scripture/usj/node-utils.test.ts, packages/shared/nodes/scripture/usj/node.utils.ts
- allow static functions to have an undefined marker argument
=> fix startsWith on undefined error

packages/platform/README.md, packages/platform/package.json, packages/platform/src/AnnotationTypeSelect.tsx, packages/platform/src/App.css, packages/platform/src/App.tsx, packages/platform/src/Editorial.tsx, packages/platform/src/editor/Editor.tsx, packages/platform/src/marginal/Marginal.tsx, packages/shared-react/annotation/AnnotationPlugin.tsx, packages/shared-react/annotation/selection.utils.ts, packages/shared-react/plugins/EditablePlugin.tsx, packages/shared-react/plugins/HistoryPlugin.tsx, packages/shared-react/plugins/text-direction.model.ts, packages/shared/nodes/scripture/usj/index.ts
- add `getSelection` function to the editor API
- add cursor location controls
- add annotation controls
- add `isReadonly` option checkbox
- improve README
- rename P.B to 'Platform' with website link
- also improve ParaNode replacement
=> platform: add controls for demo/testing

packages/platform/README.md, packages/platform/src/App.tsx, packages/platform/src/Editorial.tsx, packages/platform/src/editor/Editor.tsx, packages/platform/src/editor/ScriptureReferencePlugin.tsx, packages/platform/src/marginal/Marginal.tsx, packages/shared-react/annotation/AnnotationPlugin.tsx, packages/shared-react/plugins/UpdateStatePlugin.tsx, packages/shared/nodes/scripture/usj/node.utils.ts
- rename `onChange` property to `onUsjChange`
- rename `setScrRef` property to `onScrRefChange`
- use tag constants
=> refactor `onChange`

packages/platform/src/editor/Editor.tsx, packages/platform/src/editor/ScriptureReferencePlugin.tsx, packages/platform/src/editor/adaptors/editor-usj-adaptor.test.ts, packages/platform/src/editor/adaptors/editor-usj.adaptor.ts, packages/platform/src/editor/adaptors/usj-editor.adaptor.ts, packages/platform/src/editor/adaptors/view-options.utils.ts, packages/scribe/src/adaptors/editor-usj.adaptor.ts, packages/scribe/src/adaptors/note-usj-editor.adaptor.ts, packages/scribe/src/adaptors/usj-editor.adaptor.ts, packages/scribe/src/adaptors/view-options.utils.ts, packages/scribe/src/components/Editor.tsx, packages/scribe/src/plugins/ScriptureReferencePlugin.tsx, packages/shared-react/nodes/scripture/usj/ImmutableVerseNode.tsx, packages/shared-react/nodes/scripture/usj/node-react-utils.test.ts, packages/shared-react/nodes/scripture/usj/node-react.utils.ts, packages/shared/nodes/scripture/usj/index.ts, packages/shared/nodes/scripture/usj/node-utils.test.ts, packages/shared/nodes/scripture/usj/node.utils.ts
- if change the Para style of a block with a verse, previously the verse number would disappear (not get re-rendered).
- change `ImmutableVerseNode` to TSX so React re-renders it.
=> fix `$setBlocksType` not rendering Decorator

.github/workflows/manual-publish.yml
Added a manual publish github workflow, to publish a specific package of scribe for scribe app v1.
=> Add manual publish workflow

nx.json
- also update cache setting location
=> fix `serve` and `preview` build dependencies

packages/shared-react/plugins/TextDirectionPlugin.tsx, packages/shared-react/plugins/text-direction.model.ts
- remove cascaded update through command
=> simplify text direction

packages/perf-vanilla/src/main.ts, packages/shared/plugins/PerfOperations/updatePerfHistory.ts
- fix compile error on unneeded "??"
- update pulling the same Scripture data as `perf-react`
=> fix `perf-vanilla` not running

packages/platform/package.json, packages/platform/src/App.tsx, packages/platform/src/editor/ScriptureReferencePlugin.tsx, packages/scribe/src/plugins/ScriptureReferencePlugin.tsx, packages/shared-react/nodes/scripture/usj/node-react-utils.test.ts, packages/shared-react/nodes/scripture/usj/node-react.utils.ts, pnpm-lock.yaml
- fixes paranext/paranext-core#1201
=> fix cursor in combined verses

package.json, packages/shared/package.json, packages/utilities/package.json, packages/utilities/src/converters/usj/usj-to-usx.ts, packages/utilities/src/converters/usj/usx-to-usj.ts, pnpm-lock.yaml
- fixes #201
- `pnpm update`
- update some security dependencies
- bump `scripture-utilities` version
- also update pnpm version
=> update dependencies & utilities

packages/shared/package.json, packages/shared/utils/usfm/getMarkerAction.ts, pnpm-lock.yaml
- use the right `$is...` functions
=> fix `getMarkerAction` for mark nodes

packages/shared-react/plugins/clipboard.utils.ts, packages/utilities/package.json
- fixes #213
- replace tabs with spaces
- also remove `package.json` from utilities dist
=> fix pasting tabs

packages/platform/src/editor/ScriptureReferencePlugin.tsx, packages/platform/src/marginal/comments/CommentPlugin.tsx, packages/scribe/src/plugins/ScriptureReferencePlugin.tsx, packages/shared-react/annotation/AnnotationPlugin.tsx, packages/shared-react/plugins/NoteNodePlugin.tsx
- fixes #217
- fix breaking changes from Lexical v0.21.0
- also use react Ref for `hasSelectionChanged` variable
- also change some `for` loops to `for...of`
=> fix cursor jumping

.github/workflows/test-publish.yml
- change to the same as other publish steps
=> fix utilities publish

packages/scribe/src/App.tsx, packages/scribe/src/adaptors/editor-usj.adaptor.ts, packages/scribe/src/adaptors/usj-editor.adaptor.ts, packages/scribe/src/adaptors/usj-marker-action.utils.ts, packages/scribe/src/components/Editor.tsx, packages/scribe/src/components/Input/TextInput.tsx, packages/scribe/src/index.css, packages/scribe/src/plugins/ScriptureReferencePlugin.tsx
Refactored Scribe eidtor without toolbar to integrate with theia editor.
=> scribe editor without toolbar

packages/platform/README.md, packages/platform/src/editor/Editor.tsx, packages/shared/styles/nodes-menu.css
- remove `setUsj` check for same as original (only check for same as modified/edited)
- update README for marker menu styles
- fix marker/nodes menu styles
=> remove `setUsj` check and fix styles

packages/platform/src/App.tsx, packages/platform/src/editor/ScriptureReferencePlugin.tsx
- for matter before chapter 1, default the chapter to 1 (rather then 0)
=> platform: fix verse location for header

packages/platform/src/App.tsx, packages/platform/src/editor/Editor.tsx, packages/platform/src/editor/ScriptureReferencePlugin.tsx, packages/platform/src/editor/adaptors/usj-marker-action.utils.ts
- instead of alias `ScriptureReference`
=> platform: use `SerializedVerseRef` type

packages/perf-react/package.json, packages/perf-vanilla/package.json, packages/platform/package.json, packages/scribe/package.json, packages/shared-react/package.json, packages/shared/nodes/DivisionMarkNode.ts, packages/shared/nodes/GraftNode.ts, packages/shared/nodes/InlineNode.ts, packages/shared/nodes/UsfmElementNode.ts, packages/shared/nodes/UsfmParagraphNode.ts, packages/shared/nodes/WrapperNode.ts, packages/shared/nodes/features/ImmutableUnmatchedNode.ts, packages/shared/nodes/features/MarkerNode.ts, packages/shared/nodes/features/TypedMarkNode.ts, packages/shared/nodes/features/UnknownNode.ts, packages/shared/nodes/scripture/usj/BookNode.ts, packages/shared/nodes/scripture/usj/ChapterNode.ts, packages/shared/nodes/scripture/usj/CharNode.ts, packages/shared/nodes/scripture/usj/ImmutableChapterNode.ts, packages/shared/nodes/scripture/usj/ImpliedParaNode.ts, packages/shared/nodes/scripture/usj/MilestoneNode.ts, packages/shared/nodes/scripture/usj/NoteNode.ts, packages/shared/nodes/scripture/usj/ParaNode.ts, packages/shared/nodes/scripture/usj/VerseNode.ts, packages/shared/nodes/usfm/UsfmElementNode.ts, packages/shared/package.json, packages/utilities/package.json, pnpm-lock.yaml
- fix up nodes, see https://github.com/facebook/lexical/releases/tag/v0.23.0
=> update Lexical v0.24.0

packages/platform/src/editor/adaptors/usj-marker-action.utils.ts
- ensure leading space in CharNode is moved outside it
- fix `$getTargetNode` when selection has no leading space
=> platform: fix inserting CharNodes

package.json, packages/platform/src/editor/adaptors/usj-editor.adaptor.ts, packages/platform/src/editor/adaptors/usj-marker-action.utils.ts, packages/shared-react/plugins/NoteNodePlugin.test.tsx, packages/shared-react/plugins/NoteNodePlugin.tsx, packages/shared-react/plugins/UsjNodesMenuPlugin.test.tsx, pnpm-lock.yaml
- also fix some minor code noticed along the way
=> platform: fix note renumbering

packages/platform/.eslintrc.json, packages/scribe/src/App.tsx, packages/shared-react/.eslintrc.json, packages/shared-react/nodes/scripture/usj/node-react-utils.test.ts, packages/shared-react/plugins/CommandMenuPlugin.tsx, packages/shared-react/plugins/ContextMenuPlugin.tsx, packages/shared-react/plugins/CursorHandlerPlugin/index.tsx, packages/shared-react/plugins/FloatingBox/useCursorCoords.tsx, packages/shared-react/plugins/NodesMenu/Menu/Option.tsx, packages/shared-react/plugins/NodesMenu/NodeSelectionMenu.tsx, packages/shared-react/plugins/NoteNodePlugin.tsx, packages/shared-react/plugins/OnSelectionChangePlugin.tsx, packages/shared-react/plugins/PerfNodesItems/useUsfmMarkersForMenu.ts, packages/shared-react/plugins/PerfTypeahead/index.tsx, packages/shared-react/plugins/ScriptureReferencePlugin.tsx, packages/shared-react/plugins/UsfmNodesMenuPlugin.tsx, packages/shared-react/plugins/UsjNodesMenuPlugin.tsx
- also fix stable `nodeOptions` in Scribe
=> shared-react: fix linting

packages/platform/README.md, packages/platform/src/App.tsx, packages/shared-react/annotation/selection.model.ts, packages/shared-react/annotation/selection.utils.ts, packages/shared-react/package.json, pnpm-lock.yaml
- This partially reverts commit d8ebcfc13e679b8837c66db3bc0059772eacc371.
- `README.md`, `App.tsx`, & `selection.model.ts` were reverted,  other files modified to suit.
=> Partially revert "BREAKING CHANGE: use JSONPath indexes (#268)"

packages/platform/src/editor/adaptors/usj-marker-action-utils.test.ts, packages/platform/src/editor/adaptors/usj-marker-action.utils.ts, packages/shared-react/plugins/NoteNodePlugin.test.tsx, packages/shared-react/plugins/UsjNodesMenuPlugin.test.tsx, packages/shared/nodes/test.utils.ts
- add tests
- also fix related test functions
=> platform: fix inserting notes & chars

packages/platform/src/editor/adaptors/usj-marker-action.utils.ts, packages/shared-react/nodes/scripture/usj/node-react.utils.ts, packages/shared-react/plugins/NoteNodePlugin.tsx, packages/shared-react/plugins/ParaNodePlugin.test.tsx, packages/shared-react/plugins/ParaNodePlugin.tsx, packages/shared-react/plugins/UsjNodesMenuPlugin.tsx
- extract some functions to node utils
=> platform: no leading space in ParaNode

packages/platform/src/editor/Editor.tsx, packages/platform/src/editor/OptionChangePlugin.tsx, packages/platform/src/editor/adaptors/editor-usj-adaptor.test.ts, packages/platform/src/editor/adaptors/usj-editor-adaptor.test.ts, packages/platform/src/editor/adaptors/usj-editor.adaptor.ts, packages/shared-react/nodes/scripture/usj/ImmutableVerseNode.tsx, packages/shared-react/nodes/scripture/usj/node-react.utils.ts, packages/shared-react/plugins/NoteNodePlugin.tsx, packages/shared-react/plugins/TextDirectionPlugin.tsx, packages/shared-react/plugins/TextNodePlugin.test.tsx, packages/shared-react/plugins/TextNodePlugin.tsx, packages/shared/nodes/scripture/usj/node.utils.ts, packages/shared/nodes/test.utils.ts, packages/utilities/package.json, packages/utilities/src/converters/usj/converter-test.data.ts, packages/utilities/src/converters/usj/usj-to-usx.test.ts, packages/utilities/src/converters/usj/usj-to-usx.ts, packages/utilities/src/converters/usj/usx-to-usj.test.ts, pnpm-lock.yaml
- fix arrow keys for textDirection
- add trailing space to text if not before a NoteNode
- also fix some lint errors
=> platform: fix implied para with empty verses

apps/scriptural/src/App.tsx, apps/scriptural/src/Editor.tsx, apps/scriptural/src/app/AppBar.tsx, apps/scriptural/src/components/ScriptureNavigator.tsx, apps/scriptural/src/utils/AppReferenceHandler.ts, packages/scriptural-react/src/ScripturalEditorComposer.tsx, packages/scriptural-react/src/context/ScripturalEditorContext.tsx, packages/scriptural-react/src/index.ts, packages/scriptural-react/src/plugins/ChapterVerseUpdatePlugin/index.tsx, packages/scriptural-react/src/plugins/MarkerWatcherPlugin/index.tsx, packages/scriptural-react/src/plugins/ScrollToReferencePlugin.tsx, packages/shared/converters/usj/core/usj.d.ts, packages/shared/converters/usj/maps/usjToLexicalMap.ts, packages/shared/nodes/scripture/generic/ScriptureElementNode.ts
…al app
- Introduced `AppReferenceHandler` to manage scripture references across editors.
- Enhanced `Editor` and `AppBar` components to utilize the new reference handler.
- Added `ScriptureNavigator` component for user-friendly navigation between scripture references.
- Integrated `ScrollToReferencePlugin` to automatically scroll to the current reference in the editor.
- Updated context and props to support scripture reference handling throughout the application.
=> Implement scripture reference handling and navigation in the scriptural editor lib and app

packages/platform/src/editor/Editor.tsx, packages/scribe/src/components/Editor.tsx, packages/scribe/src/components/NoteEditor.tsx, packages/shared-react/nodes/scripture/usj/node-react.utils.ts, packages/shared-react/plugins/NoteNodePlugin.test.tsx, packages/shared-react/plugins/NoteNodePlugin.tsx, packages/shared-react/plugins/TextSpacingPlugin.test.tsx, packages/shared-react/plugins/TextSpacingPlugin.tsx, packages/shared/nodes/test.utils.ts
- keep space before verse
- remove note if caller is deleted (using backspace when note is not editable)
=> PT-3150 fix deleting note at end of verse

packages/platform/src/editor/ScriptureReferencePlugin.test.tsx, packages/shared-react/nodes/scripture/usj/ImmutableNoteCallerNode.tsx, packages/shared-react/nodes/scripture/usj/ImmutableVerseNode.tsx, packages/shared-react/plugins/ArrowNavigationPlugin.test.tsx, packages/shared-react/plugins/ArrowNavigationPlugin.tsx, packages/shared-react/plugins/NoteNodePlugin.test.tsx, packages/shared-react/plugins/ParaNodePlugin.test.tsx, packages/shared-react/plugins/TextSpacingPlugin.test.tsx, packages/shared-react/plugins/UsjNodesMenuPlugin.test.tsx, packages/shared/nodes/features/ImmutableUnmatchedNode.ts, packages/shared/nodes/scripture/usj/ImmutableChapterNode.ts, packages/shared/nodes/scripture/usj/MilestoneNode.ts, packages/shared/nodes/scripture/usj/node.utils.ts
- on empty paras
- also improve test errors
=> improve arrow navigation

packages/utilities/src/converters/usj/usj-to-usx.ts, packages/utilities/src/converters/usj/usx-to-usj.ts
- also reorder functions
- also change to for-of for attributes
=> update USX/USJ converters from Python

packages/utilities/src/converters/usj/usx-to-usj.test.ts, packages/utilities/src/converters/usj/usx-to-usj.ts
- enable whitespace test
- fixes #224
=> fix whitespace content being removed

packages/platform/src/editor/adaptors/editor-usj.adaptor.ts, packages/platform/src/editor/adaptors/usj-editor-adaptor.test.ts, packages/platform/src/editor/adaptors/usj-editor.adaptor.ts, packages/shared/nodes/usj/ImpliedParaNode.ts, packages/shared/nodes/usj/index.ts, packages/utilities/src/converters/usj/converter-test.data.ts
- change default paragraph from `ParaNode` to `ImpliedParaNode`.
=> platform: default paragraph is ImpliedParaNode

packages/perf-react/package.json, packages/perf-vanilla/package.json, packages/platform/src/editor/Editor.tsx, packages/shared-react/package.json, packages/shared-react/plugins/usj/CharNodePlugin.test.tsx, packages/shared-react/plugins/usj/CharNodePlugin.tsx, packages/shared/package.json, pnpm-lock.yaml
- if they have the same marker and attributes
- also removed unused `deep-equal` package
=> platform: combine adjacent CharNodes

packages/utilities/package.json
- first release after repo rename
=> scripture-utilities v0.1.1

packages/shared/nodes/features/UnknownNode.ts
- warning: UnknownNode should implement "importDOM" if using a custom "exportDOM" method to ensure HTML serialization (important for copy & paste) works as expected
=> fix warning after Lexical update

packages/platform/package.json
- has full published types
- some BREAKING CHANGES
=> platform-editor v0.8.0

nx.json
=> improve typecheck

demos/platform/package.json, demos/platform/src/app/app.tsx
- `nx dev platform` has 1st chapter of WEB PSA and debug
- `nx dev:test platform` has all chapters of WEB PSA and no debug
=> platform: add back `dev:test` task

demos/platform/src/app/ExternalToolbar.tsx, demos/platform/src/app/app.tsx, libs/shared-react/src/nodes/usj/node-react.utils.ts, libs/shared-react/src/plugins/usj/NoteNodePlugin.test.tsx, libs/shared-react/src/plugins/usj/NoteNodePlugin.tsx, libs/shared-react/src/plugins/usj/collab/delta-apply-update.utils.ts, libs/shared/src/nodes/usj/NoteNode.ts, libs/shared/src/nodes/usj/node.utils.ts, packages/platform/README.md, packages/platform/src/editor/Editor.tsx, packages/platform/src/editor/adaptors/usj-editor.adaptor.ts, packages/platform/src/editor/adaptors/usj-marker-action-utils.test.ts, packages/platform/src/editor/adaptors/usj-marker-action.utils.ts, packages/platform/src/marginal/Marginal.tsx, packages/scribe/src/editor/Editor.tsx, packages/scribe/src/editor/NoteEditor.tsx
- update functionality in marker menu to match
=> PT-3480: insert note API
