packages/platform/README.md
packages/platform/package.json
packages/platform/src/App.tsx
packages/platform/src/editor/Editor.tsx
packages/platform/src/editor/adaptors/editor-usj-adaptor.test.ts
packages/platform/src/editor/adaptors/editor-usj.adaptor.ts
packages/platform/src/editor/use-deferred-state.hook.ts
packages/platform/src/index.ts
packages/shared-react/plugins/UpdateStatePlugin.tsx
packages/shared/converters/usj/converter-test.data.ts
packages/shared/converters/usj/usj-to-usx.test.ts
pnpm-lock.yaml

- defer USJ updates to platform editor.
- fix round trip.
- removed properties that are undefined.
- remove empty content arrays.
- also move `lexical` to dependencies (no longer - bundled in editor package) .
- also clear timeout on `UpdateStatePlugin` exit.
- fixes #44.

uncontrolled USJ props

---

packages/platform/src/App.tsx
packages/platform/src/editor/ScriptureReferencePlugin.tsx
packages/platform/src/editor/adaptors/usj-editor-adaptor.test.ts
packages/platform/src/editor/adaptors/view-options.utils.ts
packages/platform/src/editor/toolbar/view-mode.model.ts
packages/platform/src/index.ts

- fixes #68
- fix view mode consts to be UPPER_CAMEL case
- also export `DEFAULT_VIEW_MODE`

allow `viewOptions` to be actually optional

---

packages/platform/src/editor/toolbar/BlockFormatDropDown.tsx

- retain the existing ParaNode `classList` values when formatting the block

fix block format classes

---

README.md
packages/scribe/package.json
pnpm-lock.yaml

- remove `platform` dependency
- add Scribe to the README structure graph

Scribe cleanup

---

packages/platform/src/editor/Editor.tsx
packages/platform/src/editor/editor.css
packages/platform/src/editor/toolbar/ToolbarPlugin.tsx
packages/platform/src/marginal/Marginal.tsx
packages/platform/src/marginal/comments/CommentPlugin.css
packages/platform/src/marginal/comments/CommentPlugin.tsx

- always show `AddCommentBox` & `ShowCommentsButton`
- sidebar appears beside text
- move `showComments` to toolbar

Platform comment tidy up

---

packages/platform/package.json
packages/platform/tsconfig.node.json
packages/platform/vite.config.ts
packages/shared/converters/usj/usj-to-usx.ts
packages/shared/converters/usj/usj.model.ts
packages/shared/converters/usj/usx-to-usj.ts

- exclude dependencies from being bundled
- deprecate converters in favor of where they have been moved to

platform-editor v0.3.1

---

packages/perf-react/src/app/Editor.tsx
packages/platform/src/editor/Editor.tsx
packages/platform/src/marginal/comments/CommentPlugin.tsx
packages/scribe/src/components/Editor.tsx
packages/scribe/src/components/NoteEditor.tsx

- replace default import with named import.

fix deprecated `LexicalErrorBoundary` import

---

packages/platform/src/editor/adaptors/editor-usj.adaptor.ts
packages/platform/src/editor/adaptors/usj-editor.adaptor.ts
packages/scribe/src/adaptors/editor-usj.adaptor.ts
packages/scribe/src/adaptors/note-usj-editor.adaptor.ts
packages/scribe/src/adaptors/usj-editor.adaptor.ts
packages/shared-react/plugins/NoteNodePlugin.tsx
packages/shared/nodes/scripture/usj/ImmutableVerseNode.ts
packages/shared/nodes/scripture/usj/node.utils.ts
packages/utilities/src/converters/usj/converter-test.data.ts

- add ZWSP after verse number so double-clicking first word after the number only selects that word
- add ZWSP as list child of NoteNode so double-clicking first word after the note only selects that word
- also remove undefined properties from `serializedEditorState` to improve debugging

Fix #128 double-click selection

---

packages/platform/src/editor/adaptors/editor-usj.adaptor.ts
packages/platform/src/editor/adaptors/usj-editor.adaptor.ts
packages/shared/nodes/scripture/usj/ImmutableUnmatchedNode.ts
packages/shared/nodes/scripture/usj/index.ts
packages/shared/nodes/scripture/usj/node.utils.ts
packages/utilities/src/converters/usj/converter-test.data.ts

- displays an invalid unmatched node to the user, usually a closing marker without a corresponding opening marker

add UnmatchedNode

---

packages/utilities/src/converters/usj/converter-test.data.ts
packages/utilities/src/converters/usj/usj-to-usx.ts

- `<unmatched />` node should only have attribute `marker` (not `style`)

fix unmatched in USX

---

packages/shared-react/plugins/CommandMenuPlugin.tsx

- ignore forward slash keypress and if contained in paste or drag

platform: prevent forward slash

---

packages/platform/README.md

Platform.Bible was rebranded to be "Platform". It's keeping the website https://platform.bible.

Update Platform name in README.md

---

packages/platform/src/marginal/comments/CommentPlugin.tsx
packages/platform/src/marginal/comments/commenting.ts

- previously the timestamp was relative to time when navigation has started in the window context.

platform: fix comment timestamp

---

.vscode/settings.json
packages/platform/src/editor/adaptors/editor-usj.adaptor.ts
packages/platform/src/editor/adaptors/usj-editor.adaptor.ts
packages/scribe/src/adaptors/editor-usj.adaptor.ts
packages/scribe/src/adaptors/note-usj-editor.adaptor.ts
packages/scribe/src/adaptors/usj-editor.adaptor.ts
packages/shared-react/plugins/NoteNodePlugin.tsx
packages/shared-react/plugins/TextDirectionPlugin.tsx
packages/shared/nodes/scripture/usj/node.utils.ts
packages/utilities/src/converters/usj/converter-test.data.ts

- fixes paranext/paranext-core#1258
- double-clicking a word after a note node (no space between) only selects the word
- When moving forward with arrow keys, if a note node is next, move to the following node.
- also simplify arrow keys in text direction plugin
- also don't search in `lib` folder

fix double-click word after note node

---

packages/platform/vite.config.ts
packages/scribe/src/plugins/ScriptureReferencePlugin.tsx
packages/scribe/vite.config.ts

- Previously package `index.d.ts` files that imported `scripture-utilities` imported `... from '../../../utilities/src';`. Now they import `... from '@biblionexus-foundation/scripture-utilities';`.

fix `index.d.ts` that import `scripture-utilities`

---

packages/platform/package.json
packages/scribe/package.json
pnpm-lock.yaml

- for package versions <1.0.0,  `^` won't allow patch upgrades but `~` will.

fix upgrades for `scripture-utilities`

---

packages/shared/data/WEB-PSA.usx.ts
packages/shared/data/psa.usfm.usx.ts

- after updating `@xmldom/xmldom` from v0.8.10 to v0.9.5 it is stricter about the first line.

platform: fix App start error

---

.prettierignore
packages/shared/utils/usfm/usfmMarkers.ts
packages/shared/utils/usfm/usfmTypes.ts
tools/usfm-markers/README.md
tools/usfm-markers/src/generators/markers-data/files/src/usfmMarkers.ts.template
tools/usfm-markers/src/generators/markers-data/files/src/usfmTypes.ts.template
tools/usfm-markers/src/generators/markers-data/generator.ts
tools/usfm-markers/src/generators/markers-data/utils/simplifyMarkersDictionary.ts

- don't format files since it removes comments from `tsconfig.base.json` and PRs check formatting anyway
- add comment to files stating they are generated
- allow for `usfm.sty` properties to not exist. This allows us to parse https://raw.githubusercontent.com/usfm-bible/tcdocs/refs/heads/main/grammar/usfm3_1.sty

improve `markers-data` generator

---

packages/platform/src/editor/Editor.tsx
packages/platform/src/editor/ScriptureReferencePlugin.tsx
packages/platform/src/editor/adaptors/editor-usj.adaptor.ts
packages/platform/src/editor/adaptors/usj-editor.adaptor.ts
packages/platform/src/editor/adaptors/view-options.utils.ts
packages/scribe/src/adaptors/editor-usj.adaptor.ts
packages/scribe/src/adaptors/note-usj-editor.adaptor.ts
packages/scribe/src/adaptors/usj-editor.adaptor.ts
packages/scribe/src/adaptors/view-options.utils.ts
packages/shared-react/annotation/AnnotationPlugin.tsx
packages/shared-react/nodes/scripture/usj/ImmutableVerseNode.tsx
packages/shared-react/nodes/scripture/usj/node-react.utils.ts
packages/shared-react/plugins/UpdateStatePlugin.tsx
packages/shared/adaptors/scr-ref.model.ts
packages/shared/nodes/features/ImmutableUnmatchedNode.ts
packages/shared/nodes/features/UnknownNode.ts
packages/shared/nodes/scripture/usj/BookNode.ts
packages/shared/nodes/scripture/usj/ChapterNode.ts
packages/shared/nodes/scripture/usj/CharNode.ts
packages/shared/nodes/scripture/usj/ImmutableChapterNode.ts
packages/shared/nodes/scripture/usj/MilestoneNode.ts
packages/shared/nodes/scripture/usj/NoteNode.ts
packages/shared/nodes/scripture/usj/ParaNode.ts
packages/shared/nodes/scripture/usj/VerseNode.ts
packages/shared/nodes/scripture/usj/node-constants.ts
packages/shared/nodes/scripture/usj/node.utils.ts

- add `node-constants.ts` to relieve circular dependency
- add `scr-ref.model.ts` since PBR isn't a dependency
- add utility to check if a node has a `getMarker` method

remove circular dependency

---

packages/platform/src/editor/Editor.tsx
packages/platform/src/editor/toolbar/BlockFormatDropDown.tsx
packages/shared-react/plugins/ParaNodePlugin.tsx
packages/shared/utils/usfm/usfmMarkersOverwrites.ts

- can only edit 'b' ParaNode if it already contains text.
- include 'b' (blank line) marker in Marker/Node menu
- 'b' marker no longer selectable in block menu

can't edit b marker

---

packages/platform/src/editor/Editor.tsx
packages/platform/src/editor/ScriptureReferencePlugin.tsx
packages/platform/src/editor/adaptors/view-options.utils.ts
packages/scribe/src/adaptors/view-options.utils.ts
packages/scribe/src/components/Editor.tsx
packages/scribe/src/plugins/ScriptureReferencePlugin.tsx
packages/shared-react/nodes/scripture/usj/node-react-utils.test.ts
packages/shared-react/nodes/scripture/usj/node-react.utils.ts
packages/shared-react/plugins/UsjNodesMenuPlugin.tsx
packages/shared/nodes/scripture/usj/node.utils.ts

- renumber only in the current chapter
- refactor node utils to not need the node class or type
- fix numbering when inserting a verse on a new line
- remove redundant `await`s from tests

fix verse numbering

---

package.json
packages/scribe/package.json
pnpm-lock.yaml

- pnpm 10 changes how dependencies are linked across workspaces. Since this is a monorepo, make sure the prettier plugin is installed at the root.

upgrade to pnpm v10

---

packages/platform/README.md
packages/platform/src/App.tsx
packages/platform/src/editor/adaptors/usj-marker-action.utils.ts
packages/shared-react/nodes/scripture/usj/node-react.utils.ts
packages/shared-react/plugins/UsjNodesMenuPlugin.test.tsx
packages/shared-react/plugins/UsjNodesMenuPlugin.tsx
packages/shared/nodes/features/TypedMarkNode.test.ts
packages/utilities/README.md

- fix renumbering if only one chapter or is last chapter
- don't include `sid` for chapter or verse
- add a space before a verse if needed
- don't renumber if new USJ is loaded
- refactor to use node transform (remove bad cascading update)
- add tests and framework
- also add `utilities` develop-in-app instructions
- also remove redundant `await`s from tests

platform: fix verse renumbering

---

packages/scribe/src/components/Editor.tsx
packages/scribe/src/plugins/FloatingBox/useCursorCoords.tsx
packages/scribe/src/plugins/NodesMenu/Menu/Option.tsx
packages/scribe/src/plugins/NodesMenu/NodeSelectionMenu.tsx
packages/scribe/src/plugins/NodesMenu/index.tsx
packages/scribe/src/plugins/PerfNodesItems/useUsfmMarkersForMenu.ts
packages/scribe/src/plugins/UsfmNodesMenuPlugin.tsx
packages/scribe/src/plugins/UsjNodesMenuPlugin.tsx
packages/shared-react/plugins/UsjNodesMenuPlugin.tsx

- React Hook dependency warnings
- wrap `handleInputSubmit` in useCallback and define it before it is used
- also de-nest else-if
- also don't need both `?` and `| undefined`
>[!NOTE]
>There are still more warnings but  you might need to look at those.

scribe: fix some lint warnings

---

packages/platform/src/editor/adaptors/usj-editor.adaptor.ts
packages/platform/src/editor/adaptors/usj-marker-action.utils.ts

- move leading spaces when inserting inline nodes
- ensure default note callers are set

platform: fix spaces & callers

---

packages/platform/README.md
packages/platform/src/App.tsx
packages/platform/src/index.ts
packages/shared-react/annotation/selection.model.ts
packages/shared-react/annotation/selection.utils.ts
packages/utilities/package.json
packages/utilities/src/converters/usj/jsonpath-indexes.test.ts
packages/utilities/src/converters/usj/jsonpath-indexes.ts
packages/utilities/src/index.ts

- use JSONPath indexes instead of JSONPath for USJ location
- add utilities to convert between JSONPath indexes and JSONPath (for backwards compatibility)
- also fix `package.json` build warnings
- also export more types

BREAKING CHANGE: use JSONPath indexes

---

packages/platform/src/editor/ScriptureReferencePlugin.tsx
packages/platform/src/editor/editor.css

- prevent `scrRef` updating again after the cursor has moved.
- also fix console warning about focus when `display: flex` on content editable element

platform: part of PT-2248 cursor jump

---

packages/platform/src/editor/ScriptureReferencePlugin.tsx
packages/scribe/src/plugins/ScriptureReferencePlugin.tsx
packages/shared-react/nodes/scripture/usj/node-react-utils.test.ts
packages/shared-react/nodes/scripture/usj/node-react.utils.ts
packages/shared/nodes/scripture/usj/node-utils.test.ts
packages/shared/nodes/scripture/usj/node.utils.ts

- fix off-by-one error in `removeNodesBeforeNode`, added tests
- fix `$findVerseOrPara` when in a verse range, added tests
- fix `$findVerseOrPara` when before verse one, added tests
- fix `removeNodeAndAfter`, added tests
- also fixed function names in tests

platform: fix part of PT-2248 issue

---

packages/platform/src/usj-nodes.css
packages/scribe/src/index.css
packages/shared-react/plugins/NoteNodePlugin.tsx

- when a note is removed, re-generate callers without scrolling the content editable to the top

generate callers without scroll

---

packages/platform/src/editor/adaptors/usj-editor-adaptor.test.ts
packages/platform/src/editor/adaptors/usj-editor.adaptor.ts
packages/platform/src/marginal/comments/use-missing-comments-props.hook.tsx
packages/scribe/src/adaptors/usj-editor.adaptor.ts
packages/shared-react/nodes/scripture/usj/usj-node-options.model.ts
packages/shared/nodes/features/TypedMarkNode.ts

- instead of `MarkNodeName`, missed change in earlier refactor

use `typeMarkNodeName`

---

packages/platform/src/editor/ScriptureReferencePlugin.tsx
packages/shared/nodes/scripture/usj/node-utils.test.ts
packages/shared/nodes/scripture/usj/node.utils.ts

- selecting another verse in the range of this editor in another editor shouldn't move the cursor already in the range in this editor.

platform: fix more of PT-2248 issue

---

packages/platform/src/editor/Editor.tsx
packages/scribe/src/components/Editor.tsx
packages/scribe/src/components/NoteEditor.tsx
packages/shared-react/nodes/scripture/usj/ImmutableVerseNode.tsx
packages/shared-react/plugins/ArrowNavigationPlugin.test.tsx
packages/shared-react/plugins/ArrowNavigationPlugin.tsx
packages/shared-react/plugins/NoteNodePlugin.test.tsx
packages/shared-react/plugins/NoteNodePlugin.tsx
packages/shared/nodes/scripture/usj/node.utils.ts
packages/shared/nodes/test.utils.ts

- arrow keys move over chapter and verses rather than into them
- also revert changes to `ImmutableVerseNode` from PR #295

platform: arrow key navigation

---

package.json
packages/perf-react/package.json
packages/perf-vanilla/package.json
packages/platform/package.json
packages/scribe/package.json
packages/shared-react/package.json
packages/shared/package.json
packages/utilities/package.json
pnpm-lock.yaml

Updated lexical pacakge to v0.33.0
`vite-plugin-dts` still held at `v4.5.3` due to the regression bug

update: lexical update v0.33.0

---

packages/shared-react/plugins/usj/NoteNodePlugin.test.tsx
packages/shared-react/plugins/usj/NoteNodePlugin.tsx

- properly mocks the CSS rule. Now symbol updates can be checked using the spy.

fix NoteNodePlugin test warning

---

libs/shared/src/nodes/features/TypedMarkNode.ts
packages/platform/README.md
packages/platform/src/editor/Editor.tsx
packages/platform/src/editor/editor.css
packages/utilities/src/converters/usj/converter-test.data.ts

- unique TypedMarkNode type between annotations and comments
- comments now have classnames of `editor-typed-mark-internal-comment` and `editor-typed-markOverlap-internal-comment`
- if your annotation type is "grammar" the class names are now `editor-typed-mark-external-grammar` and `editor-typed-markOverlap-external-grammar`

platform: BREAKING CHANGE: changed annotation and comment classnames

---

demos/platform/src/app/app.tsx
libs/shared-react/src/nodes/usj/ImmutableNoteCallerNode.tsx
libs/shared-react/src/nodes/usj/usj-node-options.model.ts
libs/shared-react/src/plugins/usj/NoteNodePlugin.test.tsx
libs/shared-react/src/plugins/usj/NoteNodePlugin.tsx
libs/shared-react/src/plugins/usj/collab/delta-apply-update.utils.ts
libs/shared/src/adaptors/editor-adaptor.model.ts
libs/shared/src/nodes/features/TypedMarkNode.ts
libs/shared/src/nodes/usj/NoteNode.ts
packages/platform/README.md
packages/platform/etc/platform-editor.api.md
packages/platform/src/editor/adaptors/usj-editor-adaptor.test.ts
packages/platform/src/editor/adaptors/usj-editor.adaptor.ts
packages/platform/src/index.ts
packages/platform/src/marginal/comments/use-missing-comments-props.hook.tsx
packages/scribe/README.md
packages/scribe/src/App.tsx
packages/scribe/src/editor/adaptors/note-usj-editor.adaptor.ts
packages/scribe/src/editor/adaptors/usj-editor.adaptor.ts
packages/scribe/src/index.ts

- flatten structure by removing node-specific keys
- changes API signature

BREAKING CHANGE: simplify `NodeOptions`

---

.github/workflows/test-publish.yml

- for each package you need to enable GHA as a Trusted Publisher, to set up go to e.g. https://www.npmjs.com/package/@eten-tech-foundation/platform-editor/access
- for set up details see https://docs.npmjs.com/trusted-publishers#step-1-add-a-trusted-publisher-on-npmjscom

Use npm provenance

---

packages/platform/vite.config.mts
packages/scribe/vite.config.mts
packages/utilities/vite.config.mts

- temporarily un-comment the bundle analyzer to see the analysis HTML in the `dist` folder.

reduce bundle sizes

---

packages/platform/package.json
packages/platform/project.json

- used when testing with Platform.Bible prior to publishing to npm
- fix needed after PR #355

platform: fix devpub

---

packages/platform/src/editor/editor.css

Observed Problem
----------------
Caret is difficult to see due to low contrast and a color that doesn't adapt to theme.
Described in [PT-3504](https://paratextstudio.atlassian.net/browse/PT-3504)
Expected Behavior
-----------------
Caret will be highly visible due to sufficient contrast.
How to Reproduce
----------------
1.  Apply Dark Mode
2.  Open an editor
3.  Place caret (insertion point) into editor
4.  Observe that the caret is faint (too low contrast).
Before
After
Note: This branch was committed with `--no-verify` because I couldn't get the commit hooks to work.
```
Exit status 1: husky/pre-commit: line 1: lint-staged: command not found
```

Defect: Contrast too low on caret in dark mode
